# commandservice deployment
# To deploy it to the kubernetes cluster 
# kubectl apply -f commands-depl.yaml
# list all deployments : kubectl get deployments
# list all pods : kubectl get pods
# delete a deployment : kubectl delete deployment commands-depl
# refresh docker image of a deployment : kubectl rollout restart deployment commands-depl

apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-depl
spec:
  replicas: 1
  selector: # selecting the template that we have created by the label
    matchLabels:
      app: commandservice
  template: #defining the port and container that we will use
    metadata:
      labels:
        app: commandservice
    spec:
      containers:
        - name: commandservice
          image: snaphoo/commandservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: commands-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: commandservice
  ports:
  - name:  commandservice
    port:  80
    targetPort: 80
    protocol: TCP